
trigger:
- main

pool:
  micro-agent

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Enviroment/Preproad'
    backendServiceArm: 'axion-svc'
    backendAzureRmStorageAccountName: 'infrastatestorage1407'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'dev.tfstate'
