steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: '1.16.4'

- powershell: |
    Write-Host "=== Agent identity ==="
    whoami

    Write-Host "=== Current directory ==="
    Get-Location

    Write-Host "=== Terraform exists ==="
    Test-Path "$(Agent.ToolsDirectory)\terraform\1.16.4\x64\terraform.exe"

    Write-Host "=== Terraform version ==="
    & "$(Agent.ToolsDirectory)\terraform\1.16.4\x64\terraform.exe" version

    Write-Host "=== Repo path ==="
    Write-Host "$(System.DefaultWorkingDirectory)"

    Write-Host "=== Preprod path exists ==="
    Test-Path "$(System.DefaultWorkingDirectory)\Environment\Preprod"

    Write-Host "=== Terraform files ==="
    Get-ChildItem "$(System.DefaultWorkingDirectory)\Environment\Preprod" -Filter "*.tf"
  displayName: 'Diagnose Terraform Agent'

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Preprod'
    backendServiceArm: 'axion-svc'
    backendAzureRmStorageAccountName: 'stgdev2025'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'preprod.tfstate'