trigger:
- main

pool:
  name: micro-pool

stages:
- stage: TerraformInitValidate
  displayName: Terraform Init & Validate

  jobs:
  - job: InitandValidate
    displayName: Terraform Init and Validate

    steps:

    # Install Terraform
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: '1.16.3'

    # Check Terraform installation
    - script: |
        terraform version
        where terraform
      displayName: Verify Terraform Installation

    # Terraform Init
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/preproad'
        backendServiceArm: 'axion-svc'
        backendAzureRmStorageAccountName: 'infratastorage1407'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'preproad.tfstate'

    # Terraform Validate
    - script: |
        terraform validate
      displayName: Terraform Validate
      workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/preproad'