trigger:
- main

pool:
  name: micro-agent

steps:

- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: '1.16.4'

- powershell: |
    Write-Host "=== WHO AM I ==="
    whoami

    Write-Host "=== TERRAFORM ==="
    Test-Path "$(Agent.ToolsDirectory)\terraform\1.16.4\x64\terraform.exe"
    & "$(Agent.ToolsDirectory)\terraform\1.16.4\x64\terraform.exe" version

    Write-Host "=== REPO ==="
    Write-Host "$(System.DefaultWorkingDirectory)"

    Write-Host "=== PREPROD ==="
    Test-Path "$(System.DefaultWorkingDirectory)\Environment\Preprod"

    Write-Host "=== TF FILES ==="
    Get-ChildItem "$(System.DefaultWorkingDirectory)\Environment\Preprod" -Filter "*.tf"
  displayName: Diagnose

- task: TerraformTask@5
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Preprod'
    backendServiceArm: 'axion-svc'
    backendAzureRmStorageAccountName: 'stgdev2025'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'preprod.tfstate'