
trigger:
- main

pool: micro-agent


steps:
- task: TerraformInstaller@1
  displayName: Install Terraform
  inputs:
    terraformVersion: '1.16.4'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/enviroment/preprod'
    backendServiceArm: 'Axion-SVC'
    backendAzureRmStorageAccountName: 'infrastatestorage1407'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'preprod.tfstate'

