trigger:
- main

pool:
  name: micro-pool

stages:
- stage: TerraformInitValidate
  displayName: Terraform Init & Validate

  jobs:
  - job: InitandValidate
    displayName: Terraform Init and Validate

    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Enviroment /Preproad/'
        backendServiceArm: 'axion-svc'
        backendAzureRmStorageAccountName: 'infrastatestorage1407'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'preproad-tfstate'
